In [72]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [73]:
df = pd.read_csv("C:/Users/hands/Downloads/salary_prediction.csv")
df

Experience test_scores(out of 10)  interview_score(out of 10)  salary($)
0        NaN                      8                           9      50000
1        NaN                      8                           6      45000
2       five                      6                           7      60000
3        two                     10                          10      65000
4      seven                      9                           6      70000
5      three                      7                          10      62000
6        ten                                                  7      72000
7     eleven                      7                          10      80000

In [74]:
df.Experience = df.Experience.fillna('zero')
df.replace('', np.nan, inplace=True)
df

Experience test_scores(out of 10)  interview_score(out of 10)  salary($)
0       zero                      8                           9      50000
1       zero                      8                           6      45000
2       five                      6                           7      60000
3        two                     10                          10      65000
4      seven                      9                           6      70000
5      three                      7                          10      62000
6        ten                                                  7      72000
7     eleven                      7                          10      80000

In [75]:
df.Experience = df.Experience.apply(w2n.word_to_num)
df

Experience test_scores(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                                                  7      72000
7          11                      7                          10      80000

In [76]:
import pandas as pd

# Convert the column to numeric, coerce errors to NaN
df['test_scores(out of 10)'] = pd.to_numeric(df['test_scores(out of 10)'], errors='coerce')
df

Experience  test_scores(out of 10)  interview_score(out of 10)  salary($)
0           0                     8.0                           9      50000
1           0                     8.0                           6      45000
2           5                     6.0                           7      60000
3           2                    10.0                          10      65000
4           7                     9.0                           6      70000
5           3                     7.0                          10      62000
6          10                     NaN                           7      72000
7          11                     7.0                          10      80000

In [77]:
mean_testscores = math.floor(df['test_scores(out of 10)'].mean())
mean_testscores

7

In [78]:
df['test_scores(out of 10)'] = df['test_scores(out of 10)'].fillna(mean_testscores)
df

Experience  test_scores(out of 10)  interview_score(out of 10)  salary($)
0           0                     8.0                           9      50000
1           0                     8.0                           6      45000
2           5                     6.0                           7      60000
3           2                    10.0                          10      65000
4           7                     9.0                           6      70000
5           3                     7.0                          10      62000
6          10                     7.0                           7      72000
7          11                     7.0                          10      80000

In [79]:
reg = linear_model.LinearRegression()
reg.fit(df[['Experience','test_scores(out of 10)','interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [80]:
reg.predict([[2,9,6]])

C:\Users\hands\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([54608.03445663])

In [81]:
reg.predict([[12,10,10]])

C:\Users\hands\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([91201.4608103])

In [82]:
reg.coef_

array([2714.80376249, 2297.04284387, 1787.08647124])

In [83]:
reg.intercept_

17782.522509408373

In [84]:
#implementation of the salary prediction

2714.80376249*12+2297.04284387*10+1787.08647124*10+17782.522509408373

91201.46081038837